name: Deploy Zayrova

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - uses: actions/checkout@v4

            # Install Flutter
            - uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  cache: true

            # Install dependencies
            - run: flutter pub get

            # Build for GitHub Pages
            - run: flutter build web --release --base-href "/"

            # Deploy to gh-pages
            - uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: build/web
                  cname: zayrova.ogooluwaniadewale.com
